# Generated by Django 5.2.14 on 2026-07-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='app_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='is_trusted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='local_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='os_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='tailscale_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='battery_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('phone', 'Phone'), ('tablet', 'Tablet'), ('laptop', 'Laptop'), ('desktop', 'Desktop'), ('server', 'Server'), ('raspberry_pi', 'Raspberry Pi'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('sleeping', 'Sleeping'), ('busy', 'Busy')], default='offline', max_length=20),
        ),
    ]
